baseURL = "https://jdavibedoya.github.io/"
languageCode = "en-us"
title = "David Bedoya | Audio & AI/ML Engineering"
theme = "PaperMod"
publishDir = "docs"

[params]
  defaultTheme = "auto"
  # description = "Audio & AI/ML Portfolio"
  
  [params.homeInfoParams]
    Title = "Welcome to my portfolio! ðŸ‘‹"
    Content = """
**Electronics Engineer & M.Sc. in Sound and Music Computing**. <br>
After a 5-year career as a university lecturer, I am pivoting to the tech industry to specialize as an **AI/ML Engineer**. I am currently seeking a position where I can apply my technical proficiency in **Python** and **Deep Learning**, alongside my academic discipline and problem-solving skills.
"""
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jdavibedoya"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/jdavibedoya"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 20

  [[menu.main]]
    identifier = "education"
    name = "Education"
    url = "/education/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Forzando reconstrucciÃ³n del sitio