baseURL = "https://jdavibedoya.github.io/"
languageCode = "en-us"
title = "David Bedoya | Audio, AI & Machine Learning"
theme = "PaperMod"
publishDir = "docs"

[params]
  defaultTheme = "auto"
  # description = "Audio, AI & Data Science Portfolio"
  
  [params.homeInfoParams]
    Title = "Hi there ðŸ‘‹"
    Content = "Welcome to my portfolio. I am an Electronics Engineer with a Masterâ€™s degree in Sound and Music Computing, exploring the intersection of audio, artificial intelligence, and data science."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jdavibedoya"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/jdavibedoya"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 20

  [[menu.main]]
    identifier = "education"
    name = "Education"
    url = "/education/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true